version: "3.8"

services:
  # server:
  #   image: gallery-server
  #   container_name: gallery
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.server
  #   command: yarn dev
  #   ports:
  #     - 3101:3000
  db:
    image: gallery-db:latest
    container_name: gallery-db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rachel_gallery
    ports:
      - 3102:5432