FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY server .
RUN yarn build
RUN yarn --production

FROM node:20-bullseye
COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/accounts.json /app/accounts.json
COPY --from=build /app/.env.prod /app/.env

WORKDIR /app
